services:
  message-broker:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
    volumes:
      - ./infrastructure/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      - rabbitmq-data:/var/lib/rabbitmq

  auth-db:
    image: postgres:15
    environment:
      POSTGRES_DB: AuthDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - auth-db-data:/var/lib/postgresql/data
      - ./infrastructure/sql/auth-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"

  workshop-db:
    image: postgres:15
    environment:
      POSTGRES_DB: WorkshopDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - workshop-db-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  report-db:
    image: mongo:latest
    volumes:
      - report-db-data:/data/db

volumes:
  auth-db-data:
  workshop-db-data:
  report-db-data:
  rabbitmq-data:
