CREATE TABLE "vehicles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "brand" varchar NOT NULL,
  "model" varchar NOT NULL,
  "year" int NOT NULL,
  "vin" varchar(17) UNIQUE NOT NULL,
  "photo_url" varchar,
  "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "service_orders" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "vehicle_id" int,
  "status" varchar NOT NULL,
  "assigned_mechanic_id" int,
  "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "service_tasks" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int,
  "description" varchar NOT NULL,
  "labor_cost" decimal(10,2) NOT NULL,
  "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "service_parts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int,
  "vehicle_part_id" int,
  "quantity" int NOT NULL
);

CREATE TABLE "vehicle_parts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL,
  "part_number" varchar UNIQUE NOT NULL,
  "description" varchar,
  "price" decimal(10,2),
  "available_quantity" int
);

CREATE TABLE "service_comments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int,
  "content" text,
  "created_at" timestamptz DEFAULT (now())
);

ALTER TABLE "service_orders" ADD FOREIGN KEY ("vehicle_id") REFERENCES "vehicles" ("id");

ALTER TABLE "service_tasks" ADD FOREIGN KEY ("order_id") REFERENCES "service_orders" ("id") ON DELETE CASCADE;

ALTER TABLE "service_parts" ADD FOREIGN KEY ("order_id") REFERENCES "service_orders" ("id") ON DELETE CASCADE;

ALTER TABLE "service_parts" ADD FOREIGN KEY ("vehicle_part_id") REFERENCES "vehicle_parts" ("id") ON DELETE SET NULL;

ALTER TABLE "service_comments" ADD FOREIGN KEY ("order_id") REFERENCES "service_orders" ("id") ON DELETE CASCADE;
