// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: services/auth_service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CarService {

  /// <summary>Holder for reflection information generated from services/auth_service.proto</summary>
  public static partial class AuthServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for services/auth_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AuthServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtzZXJ2aWNlcy9hdXRoX3NlcnZpY2UucHJvdG8SC2Nhcl9zZXJ2aWNlGiBt",
            "ZXNzYWdlcy9ycGNfYXV0aF9tZXNzYWdlcy5wcm90bzLlAQoLQXV0aFNlcnZp",
            "Y2USPgoFTG9naW4SGS5jYXJfc2VydmljZS5Mb2dpblJlcXVlc3QaGi5jYXJf",
            "c2VydmljZS5Mb2dpblJlc3BvbnNlEkcKCFJlZ2lzdGVyEhwuY2FyX3NlcnZp",
            "Y2UuUmVnaXN0ZXJSZXF1ZXN0Gh0uY2FyX3NlcnZpY2UuUmVnaXN0ZXJSZXNw",
            "b25zZRJNCgpWZXJpZnlVc2VyEh4uY2FyX3NlcnZpY2UuVmVyaWZ5VXNlclJl",
            "cXVlc3QaHy5jYXJfc2VydmljZS5WZXJpZnlVc2VyUmVzcG9uc2ViBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::CarService.RpcAuthMessagesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
