name: Test FileUploadService

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x 

      - name: Restore dependencies
        run: dotnet restore file-upload-service/FileUploadService.Tests/FileUploadService.Tests.csproj

      - name: Build
        run: dotnet build file-upload-service/FileUploadService.Tests/FileUploadService.Tests.csproj --no-restore

      - name: Run Tests
        run: dotnet test file-upload-service/FileUploadService.Tests/FileUploadService.Tests.csproj --no-build --logger "trx"